POST http://localhost:8181/products
Content-Type: application/json

{ "name" : "Starship", "description": "Still hot X-Wing", "price": 12, "stock": 2 }

###

POST http://localhost:8181/products/b071467a-f6ec-4135-931e-ced2609e4343/restock
Content-Type: application/json

{
  "itemsToAdd": 50
}

###

POST http://localhost:8181/products/b071467a-f6ec-4135-931e-ced2609e4343/sell
Content-Type: application/json

{
  "amountOfSoldItems": 50
}

###

